apiVersion: v1
kind: ConfigMap
metadata:
  name: illuminati-nginx-config
  namespace: { { .Values.namespace } }
data:
  frontend-nginx.conf: |
    upstream backend_service {
      server backendchart.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.backendPort }};
    }

    server {
      listen {{ .Values.service.port }} default_server;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location ^~ /api/ {
        proxy_pass http://backend_service/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
