namespace: kube-system        
serviceAccountName: external-dns
image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.19.0
  pullPolicy: Always
domainFilter: illuminaati.pp.ua
txtOwnerId: illuminati-pp-ua
awsRegion: us-east-1